name: Tests

on: [push, pull_request]

jobs:
  unit_tests:
    name: unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        rev: [nightly] 
        include:
          - os: ubuntu-latest
            install-rg: sudo apt-get update && sudo apt-get install -y ripgrep

    steps:
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: v0.12.2
      - name: Prepare
        run: |
          ${{ matrix.install-rg }}
          rg --version
      - name: Checkout plenary.nvim
        uses: actions/checkout@v6
        with:
          repository: nvim-lua/plenary.nvim
          path: ../plenary.nvim
      - name: Run tests
        run: |
          nvim --version
          make test
